// File generated by the BNF Converter (bnfc 2.9.4).

package javalette.Absyn;

public class Array  extends Type {
  public final ArrayType arraytype_;
  public Array(ArrayType p1) { arraytype_ = p1; }

  public <R,A> R accept(javalette.Absyn.Type.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof javalette.Absyn.Array) {
      javalette.Absyn.Array x = (javalette.Absyn.Array)o;
      return this.arraytype_.equals(x.arraytype_);
    }
    return false;
  }

  public int hashCode() {
    return this.arraytype_.hashCode();
  }


}
