// File generated by the BNF Converter (bnfc 2.9.4).

package javalette.Absyn;

public abstract class ArrayType implements java.io.Serializable {
  public abstract <R,A> R accept(ArrayType.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(javalette.Absyn.ArrType p, A arg);

  }

}
