// File generated by the BNF Converter (bnfc 2.9.4).

package javalette.Absyn;

public class ArrDim  extends Dim {
  public final Expr expr_;
  public ArrDim(Expr p1) { expr_ = p1; }

  public <R,A> R accept(javalette.Absyn.Dim.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof javalette.Absyn.ArrDim) {
      javalette.Absyn.ArrDim x = (javalette.Absyn.ArrDim)o;
      return this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return this.expr_.hashCode();
  }


}
