// File generated by the BNF Converter (bnfc 2.9.4).

package javalette.Absyn;

public class ArrType  extends ArrayType {
  public final Type type_;
  public ArrType(Type p1) { type_ = p1; }

  public <R,A> R accept(javalette.Absyn.ArrayType.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof javalette.Absyn.ArrType) {
      javalette.Absyn.ArrType x = (javalette.Absyn.ArrType)o;
      return this.type_.equals(x.type_);
    }
    return false;
  }

  public int hashCode() {
    return this.type_.hashCode();
  }


}
