// File generated by the BNF Converter (bnfc 2.9.4).

package javalette.Absyn;

public class Ass  extends Stmt {
  public final Lhs lhs_;
  public final Expr expr_;
  public Ass(Lhs p1, Expr p2) { lhs_ = p1; expr_ = p2; }

  public <R,A> R accept(javalette.Absyn.Stmt.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof javalette.Absyn.Ass) {
      javalette.Absyn.Ass x = (javalette.Absyn.Ass)o;
      return this.lhs_.equals(x.lhs_) && this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.lhs_.hashCode())+this.expr_.hashCode();
  }


}
