// File generated by the BNF Converter (bnfc 2.9.4).

package javalette.Absyn;

public class AssArray  extends Stmt {
  public final Index index_;
  public final Expr expr_;
  public AssArray(Index p1, Expr p2) { index_ = p1; expr_ = p2; }

  public <R,A> R accept(javalette.Absyn.Stmt.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof javalette.Absyn.AssArray) {
      javalette.Absyn.AssArray x = (javalette.Absyn.AssArray)o;
      return this.index_.equals(x.index_) && this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.index_.hashCode())+this.expr_.hashCode();
  }


}
