// File generated by the BNF Converter (bnfc 2.9.4.1).

package javalette.Absyn;

public class Block  extends Blk {
  public final ListStmt liststmt_;
  public Block(ListStmt p1) { liststmt_ = p1; }

  public <R,A> R accept(javalette.Absyn.Blk.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof javalette.Absyn.Block) {
      javalette.Absyn.Block x = (javalette.Absyn.Block)o;
      return this.liststmt_.equals(x.liststmt_);
    }
    return false;
  }

  public int hashCode() {
    return this.liststmt_.hashCode();
  }


}
