// File generated by the BNF Converter (bnfc 2.9.4).

package javalette.Absyn;

public class ELength  extends Expr {
  public final Expr expr_;
  public final String ident_;
  public ELength(Expr p1, String p2) { expr_ = p1; ident_ = p2; }

  public <R,A> R accept(javalette.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof javalette.Absyn.ELength) {
      javalette.Absyn.ELength x = (javalette.Absyn.ELength)o;
      return this.expr_.equals(x.expr_) && this.ident_.equals(x.ident_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.expr_.hashCode())+this.ident_.hashCode();
  }


}
