// File generated by the BNF Converter (bnfc 2.9.4.1).

package javalette.Absyn;

public class ELitInt  extends Expr {
  public final Integer integer_;
  public ELitInt(Integer p1) { integer_ = p1; }

  public <R,A> R accept(javalette.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof javalette.Absyn.ELitInt) {
      javalette.Absyn.ELitInt x = (javalette.Absyn.ELitInt)o;
      return this.integer_.equals(x.integer_);
    }
    return false;
  }

  public int hashCode() {
    return this.integer_.hashCode();
  }


}
