// File generated by the BNF Converter (bnfc 2.9.4).

package javalette.Absyn;

public class ELitDoub  extends Expr {
  public final Double double_;
  public ELitDoub(Double p1) { double_ = p1; }

  public <R,A> R accept(javalette.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof javalette.Absyn.ELitDoub) {
      javalette.Absyn.ELitDoub x = (javalette.Absyn.ELitDoub)o;
      return this.double_.equals(x.double_);
    }
    return false;
  }

  public int hashCode() {
    return this.double_.hashCode();
  }


}
