// File generated by the BNF Converter (bnfc 2.9.4).

package javalette.Absyn;

public class ELitArr  extends Expr {
  public final Type type_;
  public final ListDim listdim_;
  public ELitArr(Type p1, ListDim p2) { type_ = p1; listdim_ = p2; }

  public <R,A> R accept(javalette.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof javalette.Absyn.ELitArr) {
      javalette.Absyn.ELitArr x = (javalette.Absyn.ELitArr)o;
      return this.type_.equals(x.type_) && this.listdim_.equals(x.listdim_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.type_.hashCode())+this.listdim_.hashCode();
  }


}
