// File generated by the BNF Converter (bnfc 2.9.4).

package javalette.Absyn;

public class ELitArr  extends Expr {
  public final ArrayType arraytype_;
  public final Expr expr_;
  public ELitArr(ArrayType p1, Expr p2) { arraytype_ = p1; expr_ = p2; }

  public <R,A> R accept(javalette.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof javalette.Absyn.ELitArr) {
      javalette.Absyn.ELitArr x = (javalette.Absyn.ELitArr)o;
      return this.arraytype_.equals(x.arraytype_) && this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.arraytype_.hashCode())+this.expr_.hashCode();
  }


}
