// File generated by the BNF Converter (bnfc 2.9.4).

package javalette.Absyn;

public abstract class Lhs implements java.io.Serializable {
  public abstract <R,A> R accept(Lhs.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(javalette.Absyn.LhsVar p, A arg);
    public R visit(javalette.Absyn.LhsArray p, A arg);

  }

}
