// File generated by the BNF Converter (bnfc 2.9.4.1).

package javalette.Absyn;

public class Program  extends Prog {
  public final ListTopDef listtopdef_;
  public Program(ListTopDef p1) { listtopdef_ = p1; }

  public <R,A> R accept(javalette.Absyn.Prog.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof javalette.Absyn.Program) {
      javalette.Absyn.Program x = (javalette.Absyn.Program)o;
      return this.listtopdef_.equals(x.listtopdef_);
    }
    return false;
  }

  public int hashCode() {
    return this.listtopdef_.hashCode();
  }


}
