// File generated by the BNF Converter (bnfc 2.9.4.1).

package javalette.Absyn;

public abstract class Type implements java.io.Serializable {
  public abstract <R,A> R accept(Type.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(javalette.Absyn.Int p, A arg);
    public R visit(javalette.Absyn.Doub p, A arg);
    public R visit(javalette.Absyn.Bool p, A arg);
    public R visit(javalette.Absyn.Void p, A arg);
    public R visit(javalette.Absyn.Fun p, A arg);

  }

}
