// File generated by the BNF Converter (bnfc 2.9.4).

package javalette;

public class PrettyPrinter
{
  //For certain applications increasing the initial size of the buffer may improve performance.
  private static final int INITIAL_BUFFER_SIZE = 128;
  private static final int INDENT_WIDTH = 2;
  //You may wish to change the parentheses used in precedence.
  private static final String _L_PAREN = new String("(");
  private static final String _R_PAREN = new String(")");
  //You may wish to change render
  private static void render(String s)
  {
    if (s.equals("{"))
    {
       onEmptyLine();
       buf_.append(s);
       _n_ = _n_ + INDENT_WIDTH;
       buf_.append("\n");
       indent();
    }
    else if (s.equals("(") || s.equals("["))
       buf_.append(s);
    else if (s.equals(")") || s.equals("]"))
    {
       removeTrailingWhitespace();
       buf_.append(s);
       buf_.append(" ");
    }
    else if (s.equals("}"))
    {
       _n_ = _n_ - INDENT_WIDTH;
       onEmptyLine();
       buf_.append(s);
       buf_.append("\n");
       indent();
    }
    else if (s.equals(","))
    {
       removeTrailingWhitespace();
       buf_.append(s);
       buf_.append(" ");
    }
    else if (s.equals(";"))
    {
       removeTrailingWhitespace();
       buf_.append(s);
       buf_.append("\n");
       indent();
    }
    else if (s.equals("")) return;
    else if (s.trim().equals(""))
    {
       backup();
       buf_.append(s);
    }
    else
    {
       buf_.append(s);
       buf_.append(" ");
    }
  }


  //  print and show methods are defined for each category.
  public static String print(javalette.Absyn.Prog foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(javalette.Absyn.Prog foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(javalette.Absyn.TopDef foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(javalette.Absyn.TopDef foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(javalette.Absyn.ListTopDef foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(javalette.Absyn.ListTopDef foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(javalette.Absyn.Arg foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(javalette.Absyn.Arg foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(javalette.Absyn.ListArg foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(javalette.Absyn.ListArg foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(javalette.Absyn.Blk foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(javalette.Absyn.Blk foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(javalette.Absyn.ListStmt foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(javalette.Absyn.ListStmt foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(javalette.Absyn.Stmt foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(javalette.Absyn.Stmt foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(javalette.Absyn.Item foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(javalette.Absyn.Item foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(javalette.Absyn.ListItem foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(javalette.Absyn.ListItem foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(javalette.Absyn.Type foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(javalette.Absyn.Type foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(javalette.Absyn.ListType foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(javalette.Absyn.ListType foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(javalette.Absyn.Expr foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(javalette.Absyn.Expr foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(javalette.Absyn.Dim foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(javalette.Absyn.Dim foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(javalette.Absyn.ListDim foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(javalette.Absyn.ListDim foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(javalette.Absyn.ListExpr foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(javalette.Absyn.ListExpr foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(javalette.Absyn.Lhs foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(javalette.Absyn.Lhs foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(javalette.Absyn.Index foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(javalette.Absyn.Index foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(javalette.Absyn.AddOp foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(javalette.Absyn.AddOp foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(javalette.Absyn.MulOp foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(javalette.Absyn.MulOp foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(javalette.Absyn.RelOp foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(javalette.Absyn.RelOp foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  /***   You shouldn't need to change anything beyond this point.   ***/

  private static void pp(javalette.Absyn.Prog foo, int _i_)
  {
    if (foo instanceof javalette.Absyn.Program)
    {
       javalette.Absyn.Program _program = (javalette.Absyn.Program) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_program.listtopdef_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(javalette.Absyn.TopDef foo, int _i_)
  {
    if (foo instanceof javalette.Absyn.FnDef)
    {
       javalette.Absyn.FnDef _fndef = (javalette.Absyn.FnDef) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_fndef.type_, 0);
       pp(_fndef.ident_, 0);
       render("(");
       pp(_fndef.listarg_, 0);
       render(")");
       pp(_fndef.blk_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(javalette.Absyn.ListTopDef foo, int _i_)
  {
    ppListTopDef(foo.iterator(), _i_);
  }

  private static void ppListTopDef(java.util.Iterator<javalette.Absyn.TopDef> it, int _i_)
  {
    if (it.hasNext())
    {
      javalette.Absyn.TopDef el = it.next();
      if (!it.hasNext())
      { /* last */
        pp(el, _i_);
      }
      else
      { /* cons */
        pp(el, _i_); ppListTopDef(it, _i_);
      }
    }
  }


  private static void pp(javalette.Absyn.Arg foo, int _i_)
  {
    if (foo instanceof javalette.Absyn.Argument)
    {
       javalette.Absyn.Argument _argument = (javalette.Absyn.Argument) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_argument.type_, 0);
       pp(_argument.ident_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(javalette.Absyn.ListArg foo, int _i_)
  {
    ppListArg(foo.iterator(), _i_);
  }

  private static void ppListArg(java.util.Iterator<javalette.Absyn.Arg> it, int _i_)
  {
    if (it.hasNext())
    {
      javalette.Absyn.Arg el = it.next();
      if (!it.hasNext())
      { /* last */
        pp(el, _i_);
      }
      else
      { /* cons */
        pp(el, _i_); render(","); ppListArg(it, _i_);
      }
    }
  }


  private static void pp(javalette.Absyn.Blk foo, int _i_)
  {
    if (foo instanceof javalette.Absyn.Block)
    {
       javalette.Absyn.Block _block = (javalette.Absyn.Block) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("{");
       pp(_block.liststmt_, 0);
       render("}");
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(javalette.Absyn.ListStmt foo, int _i_)
  {
    ppListStmt(foo.iterator(), _i_);
  }

  private static void ppListStmt(java.util.Iterator<javalette.Absyn.Stmt> it, int _i_)
  {
    if (it.hasNext())
    { /* cons */
      javalette.Absyn.Stmt el = it.next();
      pp(el, _i_); ppListStmt(it, _i_);
    }
  }


  private static void pp(javalette.Absyn.Stmt foo, int _i_)
  {
    if (foo instanceof javalette.Absyn.Empty)
    {
       javalette.Absyn.Empty _empty = (javalette.Absyn.Empty) foo;
       if (_i_ > 0) render(_L_PAREN);
       render(";");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof javalette.Absyn.BStmt)
    {
       javalette.Absyn.BStmt _bstmt = (javalette.Absyn.BStmt) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_bstmt.blk_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof javalette.Absyn.Decl)
    {
       javalette.Absyn.Decl _decl = (javalette.Absyn.Decl) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_decl.type_, 0);
       pp(_decl.listitem_, 0);
       render(";");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof javalette.Absyn.Ass)
    {
       javalette.Absyn.Ass _ass = (javalette.Absyn.Ass) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_ass.lhs_, 0);
       render("=");
       pp(_ass.expr_, 0);
       render(";");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof javalette.Absyn.Incr)
    {
       javalette.Absyn.Incr _incr = (javalette.Absyn.Incr) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_incr.lhs_, 0);
       render("++");
       render(";");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof javalette.Absyn.Decr)
    {
       javalette.Absyn.Decr _decr = (javalette.Absyn.Decr) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_decr.lhs_, 0);
       render("--");
       render(";");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof javalette.Absyn.Ret)
    {
       javalette.Absyn.Ret _ret = (javalette.Absyn.Ret) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("return");
       pp(_ret.expr_, 0);
       render(";");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof javalette.Absyn.VRet)
    {
       javalette.Absyn.VRet _vret = (javalette.Absyn.VRet) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("return");
       render(";");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof javalette.Absyn.Cond)
    {
       javalette.Absyn.Cond _cond = (javalette.Absyn.Cond) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("if");
       render("(");
       pp(_cond.expr_, 0);
       render(")");
       pp(_cond.stmt_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof javalette.Absyn.CondElse)
    {
       javalette.Absyn.CondElse _condelse = (javalette.Absyn.CondElse) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("if");
       render("(");
       pp(_condelse.expr_, 0);
       render(")");
       pp(_condelse.stmt_1, 0);
       render("else");
       pp(_condelse.stmt_2, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof javalette.Absyn.While)
    {
       javalette.Absyn.While _while = (javalette.Absyn.While) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("while");
       render("(");
       pp(_while.expr_, 0);
       render(")");
       pp(_while.stmt_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof javalette.Absyn.For)
    {
       javalette.Absyn.For _for = (javalette.Absyn.For) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("for");
       render("(");
       pp(_for.type_, 0);
       pp(_for.ident_, 0);
       render(":");
       pp(_for.expr_, 0);
       render(")");
       pp(_for.stmt_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof javalette.Absyn.SExp)
    {
       javalette.Absyn.SExp _sexp = (javalette.Absyn.SExp) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_sexp.expr_, 0);
       render(";");
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(javalette.Absyn.Item foo, int _i_)
  {
    if (foo instanceof javalette.Absyn.NoInit)
    {
       javalette.Absyn.NoInit _noinit = (javalette.Absyn.NoInit) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_noinit.ident_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof javalette.Absyn.Init)
    {
       javalette.Absyn.Init _init = (javalette.Absyn.Init) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_init.ident_, 0);
       render("=");
       pp(_init.expr_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(javalette.Absyn.ListItem foo, int _i_)
  {
    ppListItem(foo.iterator(), _i_);
  }

  private static void ppListItem(java.util.Iterator<javalette.Absyn.Item> it, int _i_)
  {
    if (it.hasNext())
    {
      javalette.Absyn.Item el = it.next();
      if (!it.hasNext())
      { /* last */
        pp(el, _i_);
      }
      else
      { /* cons */
        pp(el, _i_); render(","); ppListItem(it, _i_);
      }
    }
  }


  private static void pp(javalette.Absyn.Type foo, int _i_)
  {
    if (foo instanceof javalette.Absyn.Int)
    {
       javalette.Absyn.Int _int = (javalette.Absyn.Int) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("int");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof javalette.Absyn.Doub)
    {
       javalette.Absyn.Doub _doub = (javalette.Absyn.Doub) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("double");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof javalette.Absyn.Bool)
    {
       javalette.Absyn.Bool _bool = (javalette.Absyn.Bool) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("boolean");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof javalette.Absyn.Void)
    {
       javalette.Absyn.Void _void = (javalette.Absyn.Void) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("void");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof javalette.Absyn.ArrType)
    {
       javalette.Absyn.ArrType _arrtype = (javalette.Absyn.ArrType) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_arrtype.type_, 0);
       render("[]");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof javalette.Absyn.Fun)
    {
       javalette.Absyn.Fun _fun = (javalette.Absyn.Fun) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_fun.type_, 0);
       render("(");
       pp(_fun.listtype_, 0);
       render(")");
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(javalette.Absyn.ListType foo, int _i_)
  {
    ppListType(foo.iterator(), _i_);
  }

  private static void ppListType(java.util.Iterator<javalette.Absyn.Type> it, int _i_)
  {
    if (it.hasNext())
    {
      javalette.Absyn.Type el = it.next();
      if (!it.hasNext())
      { /* last */
        pp(el, _i_);
      }
      else
      { /* cons */
        pp(el, _i_); render(","); ppListType(it, _i_);
      }
    }
  }


  private static void pp(javalette.Absyn.Expr foo, int _i_)
  {
    if (foo instanceof javalette.Absyn.EVar)
    {
       javalette.Absyn.EVar _evar = (javalette.Absyn.EVar) foo;
       if (_i_ > 6) render(_L_PAREN);
       pp(_evar.ident_, 0);
       if (_i_ > 6) render(_R_PAREN);
    }
    else     if (foo instanceof javalette.Absyn.EIndex)
    {
       javalette.Absyn.EIndex _eindex = (javalette.Absyn.EIndex) foo;
       if (_i_ > 6) render(_L_PAREN);
       pp(_eindex.index_, 0);
       if (_i_ > 6) render(_R_PAREN);
    }
    else     if (foo instanceof javalette.Absyn.ELength)
    {
       javalette.Absyn.ELength _elength = (javalette.Absyn.ELength) foo;
       if (_i_ > 6) render(_L_PAREN);
       pp(_elength.expr_, 6);
       render(".");
       pp(_elength.ident_, 0);
       if (_i_ > 6) render(_R_PAREN);
    }
    else     if (foo instanceof javalette.Absyn.ELitArr)
    {
       javalette.Absyn.ELitArr _elitarr = (javalette.Absyn.ELitArr) foo;
       if (_i_ > 6) render(_L_PAREN);
       render("new");
       pp(_elitarr.type_, 0);
       pp(_elitarr.listdim_, 0);
       if (_i_ > 6) render(_R_PAREN);
    }
    else     if (foo instanceof javalette.Absyn.ELitInt)
    {
       javalette.Absyn.ELitInt _elitint = (javalette.Absyn.ELitInt) foo;
       if (_i_ > 6) render(_L_PAREN);
       pp(_elitint.integer_, 0);
       if (_i_ > 6) render(_R_PAREN);
    }
    else     if (foo instanceof javalette.Absyn.ELitDoub)
    {
       javalette.Absyn.ELitDoub _elitdoub = (javalette.Absyn.ELitDoub) foo;
       if (_i_ > 6) render(_L_PAREN);
       pp(_elitdoub.double_, 0);
       if (_i_ > 6) render(_R_PAREN);
    }
    else     if (foo instanceof javalette.Absyn.ELitTrue)
    {
       javalette.Absyn.ELitTrue _elittrue = (javalette.Absyn.ELitTrue) foo;
       if (_i_ > 6) render(_L_PAREN);
       render("true");
       if (_i_ > 6) render(_R_PAREN);
    }
    else     if (foo instanceof javalette.Absyn.ELitFalse)
    {
       javalette.Absyn.ELitFalse _elitfalse = (javalette.Absyn.ELitFalse) foo;
       if (_i_ > 6) render(_L_PAREN);
       render("false");
       if (_i_ > 6) render(_R_PAREN);
    }
    else     if (foo instanceof javalette.Absyn.EApp)
    {
       javalette.Absyn.EApp _eapp = (javalette.Absyn.EApp) foo;
       if (_i_ > 6) render(_L_PAREN);
       pp(_eapp.ident_, 0);
       render("(");
       pp(_eapp.listexpr_, 0);
       render(")");
       if (_i_ > 6) render(_R_PAREN);
    }
    else     if (foo instanceof javalette.Absyn.EString)
    {
       javalette.Absyn.EString _estring = (javalette.Absyn.EString) foo;
       if (_i_ > 6) render(_L_PAREN);
       printQuoted(_estring.string_);
       if (_i_ > 6) render(_R_PAREN);
    }
    else     if (foo instanceof javalette.Absyn.Neg)
    {
       javalette.Absyn.Neg _neg = (javalette.Absyn.Neg) foo;
       if (_i_ > 5) render(_L_PAREN);
       render("-");
       pp(_neg.expr_, 6);
       if (_i_ > 5) render(_R_PAREN);
    }
    else     if (foo instanceof javalette.Absyn.Not)
    {
       javalette.Absyn.Not _not = (javalette.Absyn.Not) foo;
       if (_i_ > 5) render(_L_PAREN);
       render("!");
       pp(_not.expr_, 6);
       if (_i_ > 5) render(_R_PAREN);
    }
    else     if (foo instanceof javalette.Absyn.EMul)
    {
       javalette.Absyn.EMul _emul = (javalette.Absyn.EMul) foo;
       if (_i_ > 4) render(_L_PAREN);
       pp(_emul.expr_1, 4);
       pp(_emul.mulop_, 0);
       pp(_emul.expr_2, 5);
       if (_i_ > 4) render(_R_PAREN);
    }
    else     if (foo instanceof javalette.Absyn.EAdd)
    {
       javalette.Absyn.EAdd _eadd = (javalette.Absyn.EAdd) foo;
       if (_i_ > 3) render(_L_PAREN);
       pp(_eadd.expr_1, 3);
       pp(_eadd.addop_, 0);
       pp(_eadd.expr_2, 4);
       if (_i_ > 3) render(_R_PAREN);
    }
    else     if (foo instanceof javalette.Absyn.ERel)
    {
       javalette.Absyn.ERel _erel = (javalette.Absyn.ERel) foo;
       if (_i_ > 2) render(_L_PAREN);
       pp(_erel.expr_1, 2);
       pp(_erel.relop_, 0);
       pp(_erel.expr_2, 3);
       if (_i_ > 2) render(_R_PAREN);
    }
    else     if (foo instanceof javalette.Absyn.EAnd)
    {
       javalette.Absyn.EAnd _eand = (javalette.Absyn.EAnd) foo;
       if (_i_ > 1) render(_L_PAREN);
       pp(_eand.expr_1, 2);
       render("&&");
       pp(_eand.expr_2, 1);
       if (_i_ > 1) render(_R_PAREN);
    }
    else     if (foo instanceof javalette.Absyn.EOr)
    {
       javalette.Absyn.EOr _eor = (javalette.Absyn.EOr) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_eor.expr_1, 1);
       render("||");
       pp(_eor.expr_2, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(javalette.Absyn.Dim foo, int _i_)
  {
    if (foo instanceof javalette.Absyn.ArrDim)
    {
       javalette.Absyn.ArrDim _arrdim = (javalette.Absyn.ArrDim) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("[");
       pp(_arrdim.expr_, 0);
       render("]");
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(javalette.Absyn.ListDim foo, int _i_)
  {
    ppListDim(foo.iterator(), _i_);
  }

  private static void ppListDim(java.util.Iterator<javalette.Absyn.Dim> it, int _i_)
  {
    if (it.hasNext())
    {
      javalette.Absyn.Dim el = it.next();
      if (!it.hasNext())
      { /* last */
        pp(el, _i_);
      }
      else
      { /* cons */
        pp(el, _i_); ppListDim(it, _i_);
      }
    }
  }


  private static void pp(javalette.Absyn.ListExpr foo, int _i_)
  {
    ppListExpr(foo.iterator(), _i_);
  }

  private static void ppListExpr(java.util.Iterator<javalette.Absyn.Expr> it, int _i_)
  {
    if (it.hasNext())
    {
      javalette.Absyn.Expr el = it.next();
      if (!it.hasNext())
      { /* last */
        pp(el, _i_);
      }
      else
      { /* cons */
        pp(el, _i_); render(","); ppListExpr(it, _i_);
      }
    }
  }


  private static void pp(javalette.Absyn.Lhs foo, int _i_)
  {
    if (foo instanceof javalette.Absyn.LhsVar)
    {
       javalette.Absyn.LhsVar _lhsvar = (javalette.Absyn.LhsVar) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_lhsvar.ident_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof javalette.Absyn.LhsArray)
    {
       javalette.Absyn.LhsArray _lhsarray = (javalette.Absyn.LhsArray) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_lhsarray.index_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(javalette.Absyn.Index foo, int _i_)
  {
    if (foo instanceof javalette.Absyn.ArrInd)
    {
       javalette.Absyn.ArrInd _arrind = (javalette.Absyn.ArrInd) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_arrind.expr_1, 6);
       render("[");
       pp(_arrind.expr_2, 0);
       render("]");
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(javalette.Absyn.AddOp foo, int _i_)
  {
    if (foo instanceof javalette.Absyn.Plus)
    {
       javalette.Absyn.Plus _plus = (javalette.Absyn.Plus) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("+");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof javalette.Absyn.Minus)
    {
       javalette.Absyn.Minus _minus = (javalette.Absyn.Minus) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("-");
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(javalette.Absyn.MulOp foo, int _i_)
  {
    if (foo instanceof javalette.Absyn.Times)
    {
       javalette.Absyn.Times _times = (javalette.Absyn.Times) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("*");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof javalette.Absyn.Div)
    {
       javalette.Absyn.Div _div = (javalette.Absyn.Div) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("/");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof javalette.Absyn.Mod)
    {
       javalette.Absyn.Mod _mod = (javalette.Absyn.Mod) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("%");
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(javalette.Absyn.RelOp foo, int _i_)
  {
    if (foo instanceof javalette.Absyn.LTH)
    {
       javalette.Absyn.LTH _lth = (javalette.Absyn.LTH) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("<");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof javalette.Absyn.LE)
    {
       javalette.Absyn.LE _le = (javalette.Absyn.LE) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("<=");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof javalette.Absyn.GTH)
    {
       javalette.Absyn.GTH _gth = (javalette.Absyn.GTH) foo;
       if (_i_ > 0) render(_L_PAREN);
       render(">");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof javalette.Absyn.GE)
    {
       javalette.Absyn.GE _ge = (javalette.Absyn.GE) foo;
       if (_i_ > 0) render(_L_PAREN);
       render(">=");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof javalette.Absyn.EQU)
    {
       javalette.Absyn.EQU _equ = (javalette.Absyn.EQU) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("==");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof javalette.Absyn.NE)
    {
       javalette.Absyn.NE _ne = (javalette.Absyn.NE) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("!=");
       if (_i_ > 0) render(_R_PAREN);
    }

  }


  private static void sh(javalette.Absyn.Prog foo)
  {
    if (foo instanceof javalette.Absyn.Program)
    {
       javalette.Absyn.Program _program = (javalette.Absyn.Program) foo;
       render("(");
       render("Program");
       render("[");
       sh(_program.listtopdef_);
       render("]");
       render(")");
    }
  }

  private static void sh(javalette.Absyn.TopDef foo)
  {
    if (foo instanceof javalette.Absyn.FnDef)
    {
       javalette.Absyn.FnDef _fndef = (javalette.Absyn.FnDef) foo;
       render("(");
       render("FnDef");
       sh(_fndef.type_);
       sh(_fndef.ident_);
       render("[");
       sh(_fndef.listarg_);
       render("]");
       sh(_fndef.blk_);
       render(")");
    }
  }

  private static void sh(javalette.Absyn.ListTopDef foo)
  {
     for (java.util.Iterator<javalette.Absyn.TopDef> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(javalette.Absyn.Arg foo)
  {
    if (foo instanceof javalette.Absyn.Argument)
    {
       javalette.Absyn.Argument _argument = (javalette.Absyn.Argument) foo;
       render("(");
       render("Argument");
       sh(_argument.type_);
       sh(_argument.ident_);
       render(")");
    }
  }

  private static void sh(javalette.Absyn.ListArg foo)
  {
     for (java.util.Iterator<javalette.Absyn.Arg> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(javalette.Absyn.Blk foo)
  {
    if (foo instanceof javalette.Absyn.Block)
    {
       javalette.Absyn.Block _block = (javalette.Absyn.Block) foo;
       render("(");
       render("Block");
       render("[");
       sh(_block.liststmt_);
       render("]");
       render(")");
    }
  }

  private static void sh(javalette.Absyn.ListStmt foo)
  {
     for (java.util.Iterator<javalette.Absyn.Stmt> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(javalette.Absyn.Stmt foo)
  {
    if (foo instanceof javalette.Absyn.Empty)
    {
       javalette.Absyn.Empty _empty = (javalette.Absyn.Empty) foo;
       render("Empty");
    }
    if (foo instanceof javalette.Absyn.BStmt)
    {
       javalette.Absyn.BStmt _bstmt = (javalette.Absyn.BStmt) foo;
       render("(");
       render("BStmt");
       sh(_bstmt.blk_);
       render(")");
    }
    if (foo instanceof javalette.Absyn.Decl)
    {
       javalette.Absyn.Decl _decl = (javalette.Absyn.Decl) foo;
       render("(");
       render("Decl");
       sh(_decl.type_);
       render("[");
       sh(_decl.listitem_);
       render("]");
       render(")");
    }
    if (foo instanceof javalette.Absyn.Ass)
    {
       javalette.Absyn.Ass _ass = (javalette.Absyn.Ass) foo;
       render("(");
       render("Ass");
       sh(_ass.lhs_);
       sh(_ass.expr_);
       render(")");
    }
    if (foo instanceof javalette.Absyn.Incr)
    {
       javalette.Absyn.Incr _incr = (javalette.Absyn.Incr) foo;
       render("(");
       render("Incr");
       sh(_incr.lhs_);
       render(")");
    }
    if (foo instanceof javalette.Absyn.Decr)
    {
       javalette.Absyn.Decr _decr = (javalette.Absyn.Decr) foo;
       render("(");
       render("Decr");
       sh(_decr.lhs_);
       render(")");
    }
    if (foo instanceof javalette.Absyn.Ret)
    {
       javalette.Absyn.Ret _ret = (javalette.Absyn.Ret) foo;
       render("(");
       render("Ret");
       sh(_ret.expr_);
       render(")");
    }
    if (foo instanceof javalette.Absyn.VRet)
    {
       javalette.Absyn.VRet _vret = (javalette.Absyn.VRet) foo;
       render("VRet");
    }
    if (foo instanceof javalette.Absyn.Cond)
    {
       javalette.Absyn.Cond _cond = (javalette.Absyn.Cond) foo;
       render("(");
       render("Cond");
       sh(_cond.expr_);
       sh(_cond.stmt_);
       render(")");
    }
    if (foo instanceof javalette.Absyn.CondElse)
    {
       javalette.Absyn.CondElse _condelse = (javalette.Absyn.CondElse) foo;
       render("(");
       render("CondElse");
       sh(_condelse.expr_);
       sh(_condelse.stmt_1);
       sh(_condelse.stmt_2);
       render(")");
    }
    if (foo instanceof javalette.Absyn.While)
    {
       javalette.Absyn.While _while = (javalette.Absyn.While) foo;
       render("(");
       render("While");
       sh(_while.expr_);
       sh(_while.stmt_);
       render(")");
    }
    if (foo instanceof javalette.Absyn.For)
    {
       javalette.Absyn.For _for = (javalette.Absyn.For) foo;
       render("(");
       render("For");
       sh(_for.type_);
       sh(_for.ident_);
       sh(_for.expr_);
       sh(_for.stmt_);
       render(")");
    }
    if (foo instanceof javalette.Absyn.SExp)
    {
       javalette.Absyn.SExp _sexp = (javalette.Absyn.SExp) foo;
       render("(");
       render("SExp");
       sh(_sexp.expr_);
       render(")");
    }
  }

  private static void sh(javalette.Absyn.Item foo)
  {
    if (foo instanceof javalette.Absyn.NoInit)
    {
       javalette.Absyn.NoInit _noinit = (javalette.Absyn.NoInit) foo;
       render("(");
       render("NoInit");
       sh(_noinit.ident_);
       render(")");
    }
    if (foo instanceof javalette.Absyn.Init)
    {
       javalette.Absyn.Init _init = (javalette.Absyn.Init) foo;
       render("(");
       render("Init");
       sh(_init.ident_);
       sh(_init.expr_);
       render(")");
    }
  }

  private static void sh(javalette.Absyn.ListItem foo)
  {
     for (java.util.Iterator<javalette.Absyn.Item> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(javalette.Absyn.Type foo)
  {
    if (foo instanceof javalette.Absyn.Int)
    {
       javalette.Absyn.Int _int = (javalette.Absyn.Int) foo;
       render("Int");
    }
    if (foo instanceof javalette.Absyn.Doub)
    {
       javalette.Absyn.Doub _doub = (javalette.Absyn.Doub) foo;
       render("Doub");
    }
    if (foo instanceof javalette.Absyn.Bool)
    {
       javalette.Absyn.Bool _bool = (javalette.Absyn.Bool) foo;
       render("Bool");
    }
    if (foo instanceof javalette.Absyn.Void)
    {
       javalette.Absyn.Void _void = (javalette.Absyn.Void) foo;
       render("Void");
    }
    if (foo instanceof javalette.Absyn.ArrType)
    {
       javalette.Absyn.ArrType _arrtype = (javalette.Absyn.ArrType) foo;
       render("(");
       render("ArrType");
       sh(_arrtype.type_);
       render(")");
    }
    if (foo instanceof javalette.Absyn.Fun)
    {
       javalette.Absyn.Fun _fun = (javalette.Absyn.Fun) foo;
       render("(");
       render("Fun");
       sh(_fun.type_);
       render("[");
       sh(_fun.listtype_);
       render("]");
       render(")");
    }
  }

  private static void sh(javalette.Absyn.ListType foo)
  {
     for (java.util.Iterator<javalette.Absyn.Type> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(javalette.Absyn.Expr foo)
  {
    if (foo instanceof javalette.Absyn.EVar)
    {
       javalette.Absyn.EVar _evar = (javalette.Absyn.EVar) foo;
       render("(");
       render("EVar");
       sh(_evar.ident_);
       render(")");
    }
    if (foo instanceof javalette.Absyn.EIndex)
    {
       javalette.Absyn.EIndex _eindex = (javalette.Absyn.EIndex) foo;
       render("(");
       render("EIndex");
       sh(_eindex.index_);
       render(")");
    }
    if (foo instanceof javalette.Absyn.ELength)
    {
       javalette.Absyn.ELength _elength = (javalette.Absyn.ELength) foo;
       render("(");
       render("ELength");
       sh(_elength.expr_);
       sh(_elength.ident_);
       render(")");
    }
    if (foo instanceof javalette.Absyn.ELitArr)
    {
       javalette.Absyn.ELitArr _elitarr = (javalette.Absyn.ELitArr) foo;
       render("(");
       render("ELitArr");
       sh(_elitarr.type_);
       render("[");
       sh(_elitarr.listdim_);
       render("]");
       render(")");
    }
    if (foo instanceof javalette.Absyn.ELitInt)
    {
       javalette.Absyn.ELitInt _elitint = (javalette.Absyn.ELitInt) foo;
       render("(");
       render("ELitInt");
       sh(_elitint.integer_);
       render(")");
    }
    if (foo instanceof javalette.Absyn.ELitDoub)
    {
       javalette.Absyn.ELitDoub _elitdoub = (javalette.Absyn.ELitDoub) foo;
       render("(");
       render("ELitDoub");
       sh(_elitdoub.double_);
       render(")");
    }
    if (foo instanceof javalette.Absyn.ELitTrue)
    {
       javalette.Absyn.ELitTrue _elittrue = (javalette.Absyn.ELitTrue) foo;
       render("ELitTrue");
    }
    if (foo instanceof javalette.Absyn.ELitFalse)
    {
       javalette.Absyn.ELitFalse _elitfalse = (javalette.Absyn.ELitFalse) foo;
       render("ELitFalse");
    }
    if (foo instanceof javalette.Absyn.EApp)
    {
       javalette.Absyn.EApp _eapp = (javalette.Absyn.EApp) foo;
       render("(");
       render("EApp");
       sh(_eapp.ident_);
       render("[");
       sh(_eapp.listexpr_);
       render("]");
       render(")");
    }
    if (foo instanceof javalette.Absyn.EString)
    {
       javalette.Absyn.EString _estring = (javalette.Absyn.EString) foo;
       render("(");
       render("EString");
       sh(_estring.string_);
       render(")");
    }
    if (foo instanceof javalette.Absyn.Neg)
    {
       javalette.Absyn.Neg _neg = (javalette.Absyn.Neg) foo;
       render("(");
       render("Neg");
       sh(_neg.expr_);
       render(")");
    }
    if (foo instanceof javalette.Absyn.Not)
    {
       javalette.Absyn.Not _not = (javalette.Absyn.Not) foo;
       render("(");
       render("Not");
       sh(_not.expr_);
       render(")");
    }
    if (foo instanceof javalette.Absyn.EMul)
    {
       javalette.Absyn.EMul _emul = (javalette.Absyn.EMul) foo;
       render("(");
       render("EMul");
       sh(_emul.expr_1);
       sh(_emul.mulop_);
       sh(_emul.expr_2);
       render(")");
    }
    if (foo instanceof javalette.Absyn.EAdd)
    {
       javalette.Absyn.EAdd _eadd = (javalette.Absyn.EAdd) foo;
       render("(");
       render("EAdd");
       sh(_eadd.expr_1);
       sh(_eadd.addop_);
       sh(_eadd.expr_2);
       render(")");
    }
    if (foo instanceof javalette.Absyn.ERel)
    {
       javalette.Absyn.ERel _erel = (javalette.Absyn.ERel) foo;
       render("(");
       render("ERel");
       sh(_erel.expr_1);
       sh(_erel.relop_);
       sh(_erel.expr_2);
       render(")");
    }
    if (foo instanceof javalette.Absyn.EAnd)
    {
       javalette.Absyn.EAnd _eand = (javalette.Absyn.EAnd) foo;
       render("(");
       render("EAnd");
       sh(_eand.expr_1);
       sh(_eand.expr_2);
       render(")");
    }
    if (foo instanceof javalette.Absyn.EOr)
    {
       javalette.Absyn.EOr _eor = (javalette.Absyn.EOr) foo;
       render("(");
       render("EOr");
       sh(_eor.expr_1);
       sh(_eor.expr_2);
       render(")");
    }
  }

  private static void sh(javalette.Absyn.Dim foo)
  {
    if (foo instanceof javalette.Absyn.ArrDim)
    {
       javalette.Absyn.ArrDim _arrdim = (javalette.Absyn.ArrDim) foo;
       render("(");
       render("ArrDim");
       sh(_arrdim.expr_);
       render(")");
    }
  }

  private static void sh(javalette.Absyn.ListDim foo)
  {
     for (java.util.Iterator<javalette.Absyn.Dim> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(javalette.Absyn.ListExpr foo)
  {
     for (java.util.Iterator<javalette.Absyn.Expr> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(javalette.Absyn.Lhs foo)
  {
    if (foo instanceof javalette.Absyn.LhsVar)
    {
       javalette.Absyn.LhsVar _lhsvar = (javalette.Absyn.LhsVar) foo;
       render("(");
       render("LhsVar");
       sh(_lhsvar.ident_);
       render(")");
    }
    if (foo instanceof javalette.Absyn.LhsArray)
    {
       javalette.Absyn.LhsArray _lhsarray = (javalette.Absyn.LhsArray) foo;
       render("(");
       render("LhsArray");
       sh(_lhsarray.index_);
       render(")");
    }
  }

  private static void sh(javalette.Absyn.Index foo)
  {
    if (foo instanceof javalette.Absyn.ArrInd)
    {
       javalette.Absyn.ArrInd _arrind = (javalette.Absyn.ArrInd) foo;
       render("(");
       render("ArrInd");
       sh(_arrind.expr_1);
       sh(_arrind.expr_2);
       render(")");
    }
  }

  private static void sh(javalette.Absyn.AddOp foo)
  {
    if (foo instanceof javalette.Absyn.Plus)
    {
       javalette.Absyn.Plus _plus = (javalette.Absyn.Plus) foo;
       render("Plus");
    }
    if (foo instanceof javalette.Absyn.Minus)
    {
       javalette.Absyn.Minus _minus = (javalette.Absyn.Minus) foo;
       render("Minus");
    }
  }

  private static void sh(javalette.Absyn.MulOp foo)
  {
    if (foo instanceof javalette.Absyn.Times)
    {
       javalette.Absyn.Times _times = (javalette.Absyn.Times) foo;
       render("Times");
    }
    if (foo instanceof javalette.Absyn.Div)
    {
       javalette.Absyn.Div _div = (javalette.Absyn.Div) foo;
       render("Div");
    }
    if (foo instanceof javalette.Absyn.Mod)
    {
       javalette.Absyn.Mod _mod = (javalette.Absyn.Mod) foo;
       render("Mod");
    }
  }

  private static void sh(javalette.Absyn.RelOp foo)
  {
    if (foo instanceof javalette.Absyn.LTH)
    {
       javalette.Absyn.LTH _lth = (javalette.Absyn.LTH) foo;
       render("LTH");
    }
    if (foo instanceof javalette.Absyn.LE)
    {
       javalette.Absyn.LE _le = (javalette.Absyn.LE) foo;
       render("LE");
    }
    if (foo instanceof javalette.Absyn.GTH)
    {
       javalette.Absyn.GTH _gth = (javalette.Absyn.GTH) foo;
       render("GTH");
    }
    if (foo instanceof javalette.Absyn.GE)
    {
       javalette.Absyn.GE _ge = (javalette.Absyn.GE) foo;
       render("GE");
    }
    if (foo instanceof javalette.Absyn.EQU)
    {
       javalette.Absyn.EQU _equ = (javalette.Absyn.EQU) foo;
       render("EQU");
    }
    if (foo instanceof javalette.Absyn.NE)
    {
       javalette.Absyn.NE _ne = (javalette.Absyn.NE) foo;
       render("NE");
    }
  }


  private static void pp(Integer n, int _i_) { buf_.append(n); buf_.append(" "); }
  private static void pp(Double d, int _i_) { buf_.append(String.format(java.util.Locale.ROOT, "%.15g ", d)); }
  private static void pp(String s, int _i_) { buf_.append(s); buf_.append(" "); }
  private static void pp(Character c, int _i_) { buf_.append("'" + c.toString() + "'"); buf_.append(" "); }
  private static void sh(Integer n) { render(n.toString()); }
  private static void sh(Double d) { render(String.format(java.util.Locale.ROOT, "%.15g", d)); }
  private static void sh(Character c) { render("'" + c.toString() + "'"); }
  private static void sh(String s) { printQuoted(s); }

  private static void printQuoted(String s) { render("\"" + s + "\""); }

  private static void indent()
  {
    int n = _n_;
    while (n > 0)
    {
      buf_.append(' ');
      n--;
    }
  }

  private static void backup()
  {
    int prev = buf_.length() - 1;
    if (prev >= 0 && buf_.charAt(prev) == ' ')
      buf_.setLength(prev);
  }

  private static void trim()
  {
    // Trim initial spaces
    int end = 0;
    int len = buf_.length();
    while (end < len && buf_.charAt(end) == ' ')
      end++;
    buf_.delete(0, end);
    // Trim trailing spaces
    removeTrailingSpaces();
  }

  private static void removeTrailingSpaces()
  {
    int end = buf_.length();
    while (end > 0 && buf_.charAt(end-1) == ' ')
      end--;
    buf_.setLength(end);
  }

  private static void removeTrailingWhitespace()
  {
    int end = buf_.length();
    while (end > 0 && (buf_.charAt(end-1) == ' ' || buf_.charAt(end-1) == '\n'))
      end--;
    buf_.setLength(end);
  }

  private static void onEmptyLine()
  {
    removeTrailingSpaces();
    int len = buf_.length();
    if (len > 0 && buf_.charAt(len-1) != '\n') buf_.append("\n");
    indent();
  }

  private static int _n_ = 0;
  private static StringBuilder buf_ = new StringBuilder(INITIAL_BUFFER_SIZE);
}

